version: '3.8'
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: arent_dev
      POSTGRES_PASSWORD: eW91cl9wYXNzd29yZA==
      POSTGRES_DB: arent_health
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: